name: Docker Build and Push

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    name: Сборка и публикация Docker образа
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Переименование файла requirements
        run: |
          mv requirements.txt requiremens.txt

      - name: Создание рабочей директории
        run: |
          mkdir -p not_existing_folder

      - name: Логин в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Сборка и публикация
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            dashieva2202/zadanie4:latest
            dashieva2202/zadanie4:${{ github.sha }}
          build-args: |
            PYTHON_VERSION=3.11-slim
