name: Docker Build and Push

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    name: Сборка и публикация Docker образа
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Подготовка файлов
        run: |
          # Создаем временную копию Dockerfile
          cp Dockerfile Dockerfile.tmp
          # Заменяем неправильный тег на правильный
          sed -i 's/3.11-slim-wrongtag/3.11-slim/g' Dockerfile.tmp
          # Создаем requiremens.txt (с опечаткой, как в Dockerfile)
          echo "flask==3.0.0" > requiremens.txt

      - name: Логин в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Сборка и публикация
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.tmp
          push: true
          tags: |
            dashieva2202/zadanie4:latest
            dashieva2202/zadanie4:${{ github.sha }}

      - name: Очистка
        if: always()
        run: |
          rm -f Dockerfile.tmp
